name: ✨ Feature Request
description: Suggest an idea for VoiceFlow
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
projects: ["yuis-ice/1"]
assignees:
  - yuis-ice
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! ✨
        
        Please provide as much detail as possible to help us understand your request.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I have also considered...
    validations:
      required: false

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What type of feature is this?
      options:
        - User Interface Enhancement
        - New Voice/Audio Feature
        - Accessibility Improvement
        - Performance Optimization
        - Integration/API
        - Developer Experience
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my usage
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: |
        I would use this feature to...
        This would help me...
        My workflow would be improved by...
    validations:
      required: true

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Screenshots
      description: If applicable, add mockups, wireframes, or screenshots to help explain your feature request.
      placeholder: You can paste images directly here or drag and drop them.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: |
        Add any other context, examples, or references about the feature request here.
        
        Tip: You can attach images or files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Existing Issues
      description: Please confirm you have checked for existing feature requests
      options:
        - label: I have searched existing issues and this feature has not been requested before
          required: true

  - type: checkboxes
    id: implementation
    attributes:
      label: Implementation
      description: Are you interested in implementing this feature?
      options:
        - label: I would be willing to submit a PR to implement this feature
          required: false